### ISSUE TITLE
Does SmartPGP support RFC 6979 with (EC)DSA signing?

### ISSUE THREAD

**Issue by persmule** [ANSSI-FR/SmartPGP#18]
Does SmartPGP support [RFC 6979](https://tools.ietf.org/html/rfc6979) in its (EC)DSA implementation, which makes them deterministic?

**Comment by breard-r** [comment]
As far as I know, SmartPGP relies on the JavaCard implementation of cryptographic primitives (cf. [PGPKey.java](https://github.com/ANSSI-FR/SmartPGP/blob/master/src/fr/anssi/smartpgp/PGPKey.java#L672-L676)) : in this case, the [signPreComputedHash](https://docs.oracle.com/javacard/3.0.5/api/javacard/security/Signature.html#signPreComputedHash(byte[],%20short,%20short,%20byte[],%20short)) method. This makes the use of RFC 6979 dependent on the choices your card manufacturer made.
