### ISSUE TITLE
[Feitian A22] CAP loaded successfully but failed on creating instance

### ISSUE THREAD

**Issue by dogtopus** [ANSSI-FR/SmartPGP#2]
I can load the CAP file to the card using GlobalPlatformPro with `gp --load <CAP>` but the initialization always fails with SW 6985.

Strangly it seems that similar issue also exists in Yubikey's OpenPGP applet fork (https://github.com/Yubico/ykneo-openpgp/issues/45). Not sure if it is a problem with GPPro or the card or the applet (I can load and initialize other applets (e.g. ISOApplet, FluffyPGPApplet) without any problem on this card using GPPro)

Attached the log from GPPro in case anyone needs it.
```
$ gp-pro --package D27600012401 --applet D276000124010302AFAF000000000000 --create D276000124010302afafdeadbeef0000 -v -d -i
GlobalPlatformPro v0.3.9-38-g67ee76e
Running on Linux 4.12.13-1-ARCH amd64, Java 1.8.0_144 by Oracle Corporation
[DEBUG] PlaintextKeys - static keys: 
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
# Detected readers from JNA2PCSC
[*] Gemalto PC Twin Reader 00 00
SCardConnect("Gemalto PC Twin Reader 00 00", T=*) -> T=1, 3B9F958131FE9F00664653051000FF71DF0000000000EC
SCardBeginTransaction("Gemalto PC Twin Reader 00 00")
Reader: Gemalto PC Twin Reader 00 00
ATR: 3B9F958131FE9F00664653051000FF71DF0000000000EC
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B9F958131FE9F00664653051000FF71DF0000000000EC

A>> T=1 (4+0000) 00A40400 00 
A<< (0094+2) (27ms) 6F5C8408A000000003000000A550734A06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B040255650B06092B8510864864020103660C060A2B060104012A026E01029F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD AID: A000000003000000
[DEBUG] GlobalPlatform - Auto-detected GP version: GP211
[DEBUG] GlobalPlatform - Auto-detected block size: 255
***** Card info:
A>> T=1 (4+0000) 80CA9F7F 00 
A<< (0045+2) (13ms) 9F7F2A4090789286AA6066012360780903201505524090607886AA607886AA6078000000000000000000000000 9000
Card CPLC:
ICFabricator: 4090
ICType: 7892
OperatingSystemID: 86AA
OperatingSystemReleaseDate: 6066
OperatingSystemReleaseLevel: 0123
ICFabricationDate: 6078
ICSerialNumber: 09032015
ICBatchIdentifier: 0552
ICModuleFabricator: 4090
ICModulePackagingDate: 6078
ICCManufacturer: 86AA
ICEmbeddingDate: 6078
ICPrePersonalizer: 86AA
ICPrePersonalizationEquipmentDate: 6078
ICPrePersonalizationEquipmentID: 00000000
ICPersonalizer: 0000
ICPersonalizationDate: 0000
ICPersonalizationEquipmentID: 00000000
***** CARD DATA
A>> T=1 (4+0000) 80CA0066 00 
A<< (0078+2) (19ms) 664C734A06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B040255650B06092B8510864864020103660C060A2B060104012A026E0102 9000
Unknown tag: 4c
***** KEY INFO
A>> T=1 (4+0000) 80CA00E0 00 
A<< (0020+2) (18ms) E012C00401FF8010C00402FF8010C00403FF8010 9000
VER:255 ID:1 TYPE:DES3 LEN:16
VER:255 ID:2 TYPE:DES3 LEN:16
VER:255 ID:3 TYPE:DES3 LEN:16
Key version suggests factory keys
A>> T=1 (4+0008) 80500000 08 18DD5C86BB125D40 00
A<< (0028+2) (23ms) 00000000000000000000FF020020BA9A169477B99AEF85F75A8A323E 9000
[DEBUG] GlobalPlatform - Host challenge: 18DD5C86BB125D40
[DEBUG] GlobalPlatform - Card challenge: 0020BA9A169477B9
[DEBUG] GlobalPlatform - Card reports SCP02 with version 255 keys
[DEBUG] PlaintextKeys - session keys: 
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:B87D48485A1B030B19C7938D541BE8BD KCV: 31DA04
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:2E3DB96B8B231CF187D8D9857FA0F701 KCV: BE1357
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:DA5A7DA037C2A29F8CA02652660F3438 KCV: B475F3
[DEBUG] GlobalPlatform - Verified card cryptogram: 9AEF85F75A8A323E
[DEBUG] GlobalPlatform - Calculated host cryptogram: EDF41B365F9746E9
A>> T=1 (4+0016) 84820100 10 EDF41B365F9746E90A8F9BEF865E6979
A<< (0000+2) (18ms) 9000
A>> T=1 (4+0010) 84F28002 0A 4F00BD58E4560D8316DF 00
A<< (0019+2) (17ms) E3114F08A0000000030000009F700101C5019E 9000
A>> T=1 (4+0010) 84F24002 0A 4F00A3A46F5301A39E16 00
A<< (0000+2) (15ms) 6A88
A>> T=1 (4+0010) 84F22002 0A 4F00A84B2D8EC61B6819 00
A<< (0018+2) (27ms) E3104F06D276000124019F700101CE020100 9000
A>> T=1 (4+0010) 84F21002 0A 4F003A9C37753FB58695 00
A<< (0036+2) (31ms) E3224F06D276000124019F700101CE0201008410D276000124010302AFAF000000000000 9000
A>> T=1 (4+0055) 84E60C00 37 06D2760001240110D276000124010302AFAF00000000000010D276000124010302AFAFDEADBEEF0000010002C90000380700DFA446F850
A<< (0000+2) (1s364ms) 6985
pro.javacard.gp.GPException: Install for Install and make selectable failed SW: 6985
	at pro.javacard.gp.GPException.check(GPException.java:66)
	at pro.javacard.gp.GlobalPlatform.installAndMakeSelectable(GlobalPlatform.java:747)
	at pro.javacard.gp.GPTool.main(GPTool.java:628)
Install for Install and make selectable failed SW: 6985
```

**Comment by dogtopus** [comment]
By the way I am using the javacard-3.0.1 branch.

**Comment by dogtopus** [comment]
After some trial and errors, I found that replacing the `Cipher.getInstance(Cipher.ALG_RSA_PKCS1, false)` with null in [PGPKey.java](https://github.com/ANSSI-FR/SmartPGP/blob/04404d6a4ec9af067acd36bab032f9161f522317/src/fr/anssi/smartpgp/PGPKey.java#L46) makes the applet go through the initialization routine (the applet certainly became unusable after this modification)

Similar thing can also be done on [yubikey's applet](https://github.com/Yubico/ykneo-openpgp/blob/df508d799167e2667bf3488214b6df53e5f647b3/applet/src/openpgpcard/OpenPGPApplet.java#L228) by removing the same `Cipher.getInstance` call in the applet constructor.

However, this call is also present in the applet constructor of [FluffyPGPApplet](https://github.com/martinpaljak/AppletPlayground/blob/50551e0c7d2f23a423236f2123015551e922a24e/src/net/ss3t/javacard/gpg/Gpg.java#L211), but that applet can be installed without any problem

**Comment by dogtopus** [comment]
Just confirmed that this is due to insufficient space on RAM (see https://www.javacardos.com/javacardforum/viewtopic.php?t=523 for more information)
Close this for now

**Comment by dogtopus** [comment]
Some afterthoughts: The link I mentioned on the last reply mentioned another applet (GIDSApplet). Besides the regular RAM buffer, they allocated another buffer on the EEPROM and use that buffer for RAM-heavy features and use the normal RAM buffer for other features in order to (hopefully) reduce writing to the EEPROM.

Perhaps we can also implement this and make it an optional feature so that cards that have limited RAM can also be supported. (Turns out that my Feitian A22 probably also supports JavaCard 3.0.4 (!) rather than only 3.0.1 (or 2.2.2 as the vendor of my card claimed, which seems to be false) according to the website of JavaCOS, the OS release date as `gp --info` shows and the fact that I can also successfully load the master branch of SmartPGP applet onto the card. If this is true, the only thing that prevents this card from running this applet is the RAM size)

@af-anssi any thoughts?

**Comment by af-anssi** [comment]
Instead of removing `Cipher.getInstance(Cipher.ALG_RSA_PKCS1, false)`, could you try to decrease the value of `Constants.INTERNAL_BUFFER_MAX_LENGTH` to 0x200 or 0x100 for instance and see if there installation is working ?

**Comment by dogtopus** [comment]
@af-anssi yes, but it only works on the javacard-3.0.1 branch. I suspect that this is due to the extra RAM space consumed by secure messaging and ECC
