### ISSUE TITLE
Use the right register() method

### ISSUE THREAD

**Issue by martinpaljak** [ANSSI-FR/SmartPGP#20]
https://docs.oracle.com/javacard/3.0.5/api/javacard/framework/Applet.html#register(byte[],%20short,%20byte)

Otherwise it is not possible to assign the instance AID during installation.

**Comment by af-anssi** [comment]
Could you confirm that commit 89608a2 has fixed this issue and close this issue accordingly?

**Comment by martinpaljak** [comment]
Yep!

**Comment by bmunger** [comment]
Is there a reason why this, and some other commits were only done on the 3.0.1 branch and not in 3.0.4 or master?

**Comment by af-anssi** [comment]
Actually, the javacard-3.0.4 branch is systematically rebased on the javacard-3.0.1 branch, so it does include the commit (cf [commit history](https://github.com/ANSSI-FR/SmartPGP/commits/javacard-3.0.4) where the commit 89608a2 is the first commit on Jan 13, 2020).

**Comment by af-anssi** [comment]
@martinpaljak I will close the issue if it is OK for you.

**Comment by martinpaljak** [comment]
Good for me, was reporting it on behalf of a user struggling to install it with GPPro.

**Comment by af-anssi** [comment]
Thank you for reporting this issue on behalf of that user. It actually simplifies the deployment of the applet, especially at medium/large scale.
