### ISSUE TITLE
Creating RSA4096 keys on J3H145

### ISSUE THREAD

**Issue by bmunger** [ANSSI-FR/SmartPGP#21]
I have purchased a J3H145 card configured with RSA4096 support.  After SmartPGP cap installation, gpg recognizes the card correctly.  However, sending a key results in:

gpg: KEYTOCARD failed: Hardware problem

I installed the included test applet and ran the python script to test the card and it appears to have RSA4096 support.  What am I missing?

[+] Select applet... ok
[+] Test random... ok
[+] Test RSA 1024 static... ok
[+] Test RSA 1024 generate... ok
[+] Test RSA_CRT 1024 static... ok
[+] Test RSA_CRT 1024 generate... ok
[+] Test RSA 2048 static... ok
[+] Test RSA 2048 generate... ok
[+] Test RSA_CRT 2048 static... ok
[+] Test RSA_CRT 2048 generate... ok
[+] Test RSA 3072 static... ok
[+] Test RSA 3072 generate... ok
[+] Test RSA_CRT 3072 static... ok
[+] Test RSA_CRT 3072 generate... ok
[+] Test RSA 4096 static... ok
[+] Test RSA 4096 generate... ok
[+] Test RSA_CRT 4096 static... ok
[+] Test RSA_CRT 4096 generate... ok
[+] Test NIST P-256 static... ok
[-] Test NIST P-256 static (without W)... KO 0x6503
[+] Test NIST P-256 generate... ok
[+] Test NIST P-521 static... ok
[+] Test NIST P-521 generate... ok
[-] Test NIST P-521 (size = 528) static... KO 0x6F00
[-] Test NIST P-521 (size = 528) generate... KO 0x6F00
[+] Test PIN... ok

I can generate RSA4096 keys on the card from gpg --card-edit though.

**Comment by af-anssi** [comment]
In order to be able to import RSA keys of 4096 bits, the size of internal buffer must be adjusted. I just [committed](https://github.com/ANSSI-FR/SmartPGP/commit/f78db3e999a78aa790341ad5f13a6363dbc8295c) a new [section in the README](https://github.com/ANSSI-FR/SmartPGP/tree/javacard-3.0.1#importing-rsa-keys-above-2048-bits-3072-or-4096-bits).
By default, the internal buffer is not large enough to hold the private key template in CRT form.
Sorry for the inconvenience, it was not clearly documented before.

**Comment by martinbeier** [comment]
@bmunger I have/had the same issue -> keytocard breaked with SW 65 81 (memory failure)

@af-anssi thanks for tclearing up he internal buffer requirements, 
I had tested with some bigger numbers, than standard, but not that big :)
After testing with Constants.INTERNAL_BUFFER_MAX_LENGTH = 0x730 I was able to copy a RSA 4096 key to the card!

One drawback: for me: this is working only for the javacard-3.0.1 branch (without ECC stuff), 
I think it's related to insufficient memory during install on the card (for javacard-3.0.4 branch)

I'm really happy, that RSA 4096 is working and now looking forward for the ECC stuff :)

**Comment by bmunger** [comment]
I can confirm this also works.  Thank you.
