### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rollinbe** [ANSSI-FR/SmartPGP#23]
Unable to compile the cap file on Mac OS X 

Error message:  
[compile] error: Source option 6 is no longer supported. Use 7 or later.
[compile] error: Target option 6 is no longer supported. Use 7 or later.

**Comment by martinpaljak** [comment]
This will be fixed with a better message soonish, but meanwhile do use JDK8 for JavaCard work.

**Comment by martinpaljak** [comment]
See also https://github.com/martinpaljak/ant-javacard/wiki/Version-compatibility
