### ISSUE TITLE
Support for Curve25519

### ISSUE THREAD

**Issue by makkarpov** [ANSSI-FR/SmartPGP#32]
I'm not sure whether this can be done with existing JavaCards, but still: it would be nice to have. If we are lucky, it should be as simple as adding another curve constants.

YubiKey already supports it, and many software implementations too. This curve is extremely useful for SSH authentication, as it leads to very short and concise public keys due to compressed point representation.

**Comment by martinpaljak** [comment]
No publicly/easily available card support ed25519 / JC 3.1. We all know and want this, wishlist issues can not fix the absence

**Comment by af-anssi** [comment]
I close this issue and reopen issue #10 where the support of Curve25519 by SmartPGP is already explained.

**Comment by sdellava** [comment]
Can this code be merged to implement the ed25519 signature?

https://github.com/david-oswald/jc_curve25519

**Comment by martinpaljak** [comment]
Pure software implementation is a "fun thing to have" but does not have any kind of security guarantees of a native implementation, thus the explanation in #10 should be considered as final.
