### ISSUE TITLE
Factory reset does not work when APDUs are received over a logical channel

### ISSUE THREAD

**Issue by stelian42** [ANSSI-FR/SmartPGP#35]
I've discovered this while porting OpenKeyChain in order to use SmartPGP installed inside the secure element of an Android tablet.

Android OMAPI uses logical channels for communication, and SmartPGP mishandles the CLA byte encoding.

This is fixed by pull request #34

**Comment by af-anssi** [comment]
I cherry-picked your commit 48ba623b9dba95b912914115e35576874bb2f348 to push it in the javacard-3.0.1 branch as your fix also applies to this version.
Thank you for your contribution. I
