### ISSUE TITLE
Feature Request: Build without support for javacardx

### ISSUE THREAD

**Issue by EmperorArthur** [ANSSI-FR/SmartPGP#36]
While tracking down why the software would not install on my PIVKey C980 card, I noticed the code base uses the optional "javacardx" libraries.  I will be attempting more exploration of the root cause in the future, but it is worth either keeping an issue open or adding a Readme section about this using features which are not universal even on newer card versions.

Installation failure reason was 0x6438, indicating either a version problem or a missing library.

Note: A previous version of this request referenced the wrong thing.  JavaCard build systems are confusing.

**Comment by af-anssi** [comment]
Could you precise which version of JavaCard is supported by this token ?
Could you precise which version/release/tag of the SmartPGP applet you tried to install ?

**Comment by af-anssi** [comment]
FYI: you can edit the request title :)

**Comment by EmperorArthur** [comment]
Yeah, the original title change didn't save.

**Comment by EmperorArthur** [comment]
Okay, so I am new to the whole Smart Card thing and was working well into the AM, which is why this one started out a bit strange.

I found the information that "javacardx.crypto" support is optional in [this official pdf](https://docs.oracle.com/javacard/3.1/related-docs/JCCRE/JCCRE.pdf).  As such, I do recommend that be noted prominently in the README, and just close this issue.  I will open a new one with the real feature request.
