### ISSUE TITLE
Python3 scripts

### ISSUE THREAD

**Issue by duxco** [ANSSI-FR/SmartPGP#41]
It would be nice for `smartpgp-cli` & Co. to be Python3 compatible. Currently, I am using `2to3` to get it functioning on Ubuntu 20.04:
https://github.com/duxco/gpg-smartcard

**Comment by af-anssi** [comment]
Commit 1720a3494bf5938e4bbf8df564b604724642c746 should solve this issue.

**Comment by af-anssi** [comment]
FYI: this is not only in the master branch, the commit has been inserted in javacard-3.0.1 branch and all other branches have been rebased on it. So it is present in all branches.

**Comment by duxco** [comment]
Thanks, I removed to Python 2->3 conversion step out of my howto.
