### ISSUE TITLE
Checksums and signatures

### ISSUE THREAD

**Issue by duxco** [ANSSI-FR/SmartPGP#42]
I would love for releases to be signed with GnuPG and SHA-256/512 hashes to be published. You could also sign Git commits.

**Comment by af-anssi** [comment]
I will sign further tags, starting from  `v1.21-*`

**Comment by duxco** [comment]
@af-anssi I never think about signing 😉

- `~/.gitconfig`

```
[user]
	name = First Last
	email = first@last.eu
	signingKey = 0xASDFASDF
[includeIf "gitdir:~/github/"]
	path = ~/.gitconfig-github
[commit]
	gpgSign = true
[log]
	showSignature = true
```

- `~/.gitconfig-github`

```
[user]
	name = First Last
	email = meh@muh.de
	signingKey = 0xQWERQWER
```
