### ISSUE TITLE
smartpgp_sm.pdf missing

### ISSUE THREAD

**Issue by iamsarab87** [ANSSI-FR/SmartPGP#49]
Compliance with OpenPGP card 3.4 specification
The SmartPGP applet implements the complete OpenPGP card 3.4 specification, except the secure messaging related features:

Commands and responses protection is not implemented as described in the specification. Motivation and implementation details are explained in the [secure messaging document](https://github.com/ANSSI-FR/SmartPGP/blob/master/secure_messaging/smartpgp_sm.pdf);

PDF seems to be missing

**Comment by af-anssi** [comment]
Thank you for reporting this issue. The PDF has been (re-)added.
