### ISSUE TITLE
Wrong default APPLET_AID

### ISSUE THREAD

**Issue by breard-r** [ANSSI-FR/SmartPGP#7]
Hi,

As stated in the `README.md`, SmartPGP implements OpenPGP card 3.3 specification. However, in the default build.xml, the APPLET_AID refers to the 3.2 specification.
Therefore, I guess it is required to change `0x03:0x02` to `0x03:0x03`.

PS: A pull request is quite of a overhead for a one-character change. :)

**Comment by af-anssi** [comment]
You are right, I forgot to update the default AID.
Thanks for reporting !
